---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: tracing
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      name: prometheus-main
      labels:
        app: jaeger
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
    spec:
      containers:
        - name: jaeger-allinone
          image: jaegertracing/all-in-one:1.22
          args:
            - '--sampling.strategies-file=/etc/jaeger/sampling_strategies.json'
            - '--query.base-path=/jaeger'
            - '--collector.grpc.tls.enabled=false'
            - '--collector.http.tls.enabled=false'
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          ports:
            - name: webui
              containerPort: 16686
            - name: zipkin
              containerPort: 9411
            - name: jaegerudp
              containerPort: 6832
              protocol: UDP
            - name: jaegerthrift
              containerPort: 14268
            - name: jaeger
              containerPort: 14250
          resources:
            requests:
              cpu: 1500m
              memory: 1500M
            limits:
              cpu: 2500m
              memory: 2500M
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: tracing
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - port: 16686
      protocol: TCP
      name: webui
    - port: 14250
      protocol: TCP
      name: jaeger
    - port: 14268
      protocol: TCP
      name: jaegerthrift
    - port: 9411
      protocol: TCP
      name: zipkin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: tracing
spec:
  rules:
    - http:
        paths:
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: jaeger
                port:
                  name: webui
