#!/bin/bash

DOCKER_REGISTRY=${DOCKER_REGISTRY:-localhost:5000/}

CONTAINER=goplayermgr
CONTAINER_TAG=0.2.1


docker build -t "${DOCKER_REGISTRY}""${CONTAINER}":"${CONTAINER_TAG}" .
docker push "${DOCKER_REGISTRY}""${CONTAINER}":"${CONTAINER_TAG}"
