---
apiVersion: v1
kind: Service
metadata:
  name: amazeui
  labels:
    app: amazeui
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: amazeui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazeui
  labels:
    app: amazeui
spec:
  selector:
    matchLabels:
      app: amazeui
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        app: amazeui
    spec:
      containers:
        - name: amazeui
          image: "{{.Values.image.registry}}amazeui:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 5M
            limits:
              cpu: 1000m
              memory: 100M
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazeui
  labels:
    app: amazeui
spec:
  rules:
    - http:
        paths:
          - path: /amazeui
            pathType: Prefix
            backend:
              service:
                name: amazeui
                port:
                  number: 80
