---
apiVersion: v1
kind: Service
metadata:
  name: playermgr
  labels:
    app: playermgr
spec:
  ports:
    - port: 80
      targetPort: 8081
      name: playermgr
  selector:
    app: playermgr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playermgr
  labels:
    app: playermgr
spec:
  selector:
    matchLabels:
      app: playermgr
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        app: playermgr
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
    spec:
      containers:
        - name: playermgr
          image: "{{.Values.image.registry}}goplayermgr:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          args: ["serve"]
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: EXTERNAL_AUTH_URL
              value: {{.Values.auth.external_url}}
            - name: GIN_MODE
              value: debug
            - name: PLAYER_DSN_USER
              valueFrom:
                secretKeyRef:
                  name: player-pgsql
                  key: username
            - name: PLAYER_DSN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: player-pgsql
                  key: password
          resources:
            requests:
              cpu: 500m
              memory: 5M
            limits:
              cpu: 1000m
              memory: 100M
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playermgr
  labels:
    app: playermgr
spec:
  rules:
    - http:
        paths:
          - path: /api/players
            pathType: Prefix
            backend:
              service:
                name: playermgr
                port:
                  number: 80
