---
apiVersion: v1
kind: Service
metadata:
  name: mazemgr
  labels:
    app: mazemgr
spec:
  ports:
    - port: 80
      targetPort: 8082
      name: mazemgr
    - port: 9465
      targetPort: 9465
      name: metrics
  selector:
    app: mazemgr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mazemgr
  labels:
    app: mazemgr
spec:
  selector:
    matchLabels:
      app: mazemgr
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        app: mazemgr
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9465'
    spec:
      containers:
        - name: mazemgr
          image: "{{.Values.image.registry}}mazemgr:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          command: ["node"]
          args: ["main.js", "-p", "8082", "-s"]
          ports:
            - containerPort: 8082
              name: http
            - containerPort: 9465
              name: metrics
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger.tracing:14268/api/traces?format=jaeger.thrift"
            - name: LOG4JS_CONFIG
              value: "/home/node/app/log4js.json"
            - name: EXTERNAL_AUTH_URL
              value: {{.Values.auth.external_url}}
            - name: PG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: maze-pgsql
                  key: username
            - name: PG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: maze-pgsql
                  key: password
          resources:
            requests:
              cpu: 500m
              memory: 5M
            limits:
              cpu: 1000m
              memory: 100M
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mazemgr
  labels:
    app: mazemgr
spec:
  rules:
    - http:
        paths:
          - path: /api/mazes
            pathType: Prefix
            backend:
              service:
                name: mazemgr
                port:
                  number: 80
