---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  selector:
    app: pgsql
  ports:
    - port: 5432
      name: pgsql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    app: pgsql
  namespace: default
spec:
  selector:
    matchLabels:
      app: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - image: localhost:5000/pgsql:13
          imagePullPolicy: Always
          name: pgsql
          ports:
            - containerPort: 5432
              name: pgsql
          volumeMounts:
            - name: pglib-persistent-storage
              mountPath: /var/lib/postgresql
          resources:
            requests:
              cpu: 1000m
              memory: 1000M
            limits:
              cpu: 2000m
              memory: 2000M
      volumes:
        - name: pglib-persistent-storage
          persistentVolumeClaim:
            claimName: pg-local-claim
