---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      name: keycloak-main
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:12.0.4
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin
                  key: password
            - name: KEYCLOAK_LOGLEVEL
              value: DEBUG
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql
                  key: dbhost
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql
                  key: password
          ports:
            - name: webui
              containerPort: 8080
          resources:
            requests:
              cpu: 1500m
              memory: 1500M
            limits:
              cpu: 2500m
              memory: 2500M
          volumeMounts:
            - name: kcrealm
              mountPath: /etc/custom
      volumes:
        - name: kcrealm
          configMap:
            name: kcrealm
            items:
            - key: realm-export.json
              path: realm-export.json
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      protocol: TCP
      name: webui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $host;
      proxy_set_header X-Forwarded-Proto $scheme;
spec:
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  name: webui
