name: Node.js CI

on: [push]

jobs:
  build_playermgr:
    name: Build playerMgr
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./playermgr
    - run: npm run build
      working-directory: ./playermgr
    - run: npm test
      working-directory: ./playermgr
      env:
        CI: true
    - run: npm coverage
      working-directory: ./playermgr
    - run: npm pack
      working-directory: ./playermgr